# Site settings
## Change the values as needed.
title: JBlog- Programming Blog
email: Joshmoo2012@gmail.com
description: "A jekyll theme implementing material design by using muicss."
keywords: "jekyll, theme, material, muicss"
#url: "http://bitwiser.in/bitwiser-material" # the base hostname & protocol for your site
url: "https://JoshMooney.github.io/JBlog" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
paginate: 8
paginate_path: "page:num"
# Build settings
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
links:
  facebook: Josh Mooney
  twitter: brijeshb42
  email: Joshmoo2012@gmail.com
  github: JoshMooney
exclude:
  - bower_components
  - README.md
full_name: Josh

##set this to enable disqus commenting
disqus: Josh

##set this to enable google analytics
#ga_id: analyticsID
#ga_domain: bitwiser.in


gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

