# Site settings
## Change the values as needed.
title: JBlog
email: joshmoo2012@gmail.com
description: "A Place for Programming"
keywords: "jekyll, theme, material, muicss"
#url: "http://bitwiser.in/bitwiser-material" # the base hostname & protocol for your site
url: "https://JoshMooney.github.io/JBlog" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/

# Build settings
markdown: kramdown
#highlighter: pygments
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
links:
  facebook: josh.mooney.5680      #After the www.facebook.com/^Here
  twitter: twitter
  email: joshmoo2012@gmail.com    #Gmail address
  github: JoshMooney              #Github Name
exclude:
  - bower_components
  - README.md
full_name: Josh

##set this to enable disqus commenting
disqus: Josh

##set this to enable google analytics
#ga_id: analyticsID
#ga_domain: bitwiser.in

gems: [jekyll-paginate]
paginate: 8
paginate_path: "page:num"

