# Site settings
## Change the values as needed.
title: JBlog
email: brijeshb42@gmail.com
description: "A Place for Programming"
keywords: "jekyll, theme, material, muicss"
#url: "http://bitwiser.in/bitwiser-material" # the base hostname & protocol for your site
url: "https://JoshMooney.github.io/JBlog" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
paginate: 8
paginate_path: "page:num"
# Build settings
markdown: kramdown
#highlighter: pygments
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
links:
  facebook: brijeshb42
  twitter: brijeshb42
  email: brijeshb42@gmail.com
  github: brijeshb42/bitwiser-material/
exclude:
  - bower_components
  - README.md
full_name: Brijesh

##set this to enable disqus commenting
disqus: bitwiser

##set this to enable google analytics
ga_id: UA-97232992-1
ga_domain: JoshMooney.github.io/JBlog

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

